config/routes.rb
Rails.application.routes.draw do
root "inspirations#index"
devise_for :users

resources :inspirations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inspiration.rb
class Inspiration < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :inspirations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/inspirations_controller.rb
class InspirationsController < ApplicationController
  before_action :set_inspiration, only: [:show, :update, :edit, :destroy]

  def index
    @inspirations = current_user.inspirations
  end

  def show
  end

  def new
    @inspiration = Inspiration.new
  end

  def create
    @inspiration = current_user.inspirations.new(inspiration_params)
    if @inspiration.save
      redirect_to inspirations_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @inspiration.update(inspiration_params)
      redirect_to inspirations_path
    else
      render :edit
    end
  end

  def destroy
    @inspiration.destroy
    redirect_to inspirations_path
  end

  private
    def inspiration_params
      params.require(:inspiration).permit(:source, :body)
    end

    def set_inspiration
      @inspiration = current_user.inspirations.find(params[:id])
    end

end

app/helpers/inspirations_helper.rb
module InspirationsHelper
end

app/views/inspirations/edit.html.erb
<h1>Edit the inspirational source and message:</h1>
<%= form_with(model: @account, local: true) do |f| %>
  <div class="field">
    <%= f.label :source %>
    <%= f.text_field :source %>
  </div>

  <div class="field">
  <%= f.label :body %>
  <%= f.text_area :body %>
  </div>

  <%= f.submit %>
<% end %>

app/views/inspirations/index.html.erb
<%= button_to "Log Out", destroy_user_session_path, method: :delete %>
<h2>Welcome <%= current_user.first_name %></h2>
<%= link_to 'Edit User', edit_user_registration_path %>
<hr />
<%= link_to "Add Inspiration!", new_inspiration_path %>
<h3>Your Current Sources of Inspiration</h3>
<ul>
  <% @inspirations.each do |inspiration| %>
    <li>
      <%= inspiration.source %> :: <%= inspiration.body %>
    </li>
  <% end %>
</ul>

app/views/inspirations/new.html.erb
<h1>Add an inspirational source and message:</h1>
<%= form_with(model: @inspiration, local: true) do |f| %>
  <div class="field">
    <%= f.label :source %>
    <%= f.text_field :source %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <%= f.submit %>
<% end %>

app/views/inspirations/show.html.erb
<h1>This is the show page for an individual inspiration message...</h1>
<p>There's really not a whole lot going on here...</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>[DevPoint Labs] Devise Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>